server:
  port: 8081

spring:
  mvc:
    hidden-method:
      filter:
        enabled: true

url-api: "http://localhost:8080/"
url-api-token: "http://localhost:8080/token"
url-api-astronauts: "http://localhost:8080/astronauts"
url-api-expeditions: "http://localhost:8080/expeditions"
url-api-users: "http://localhost:8080/users"
