spring:
  profiles:
    active: dev
    group:
      dev:
        - local-dev
        - debug
  jpa:
    open-in-view: false
    show-sql: true
  flyway:
    clean-on-validation-error: true
server:
  error:
    include-message: always
    include-binding-errors: always
springdoc:
  show-actuator: true
management:
  endpoint:
    health:
      show-details: always