space-flight:
  security:
    jwt-properties:
      secret: eitu9aichae7eitee9XiciweishohW3pieshaifasosai5xie9Oomobulohyu8ie
      access-expire-in: 10m
      refresh-expire-in: 3d
    admins:
      space:
        email: space@flight.com
        password: $2a$10$WBxIdF./sHKCGllpn4jBBuxzok2eEbG4lMV7V74RtJhAiS2aAY.ri
spring:
  profiles:
    active: dev
    group:
      dev:
        - local-dev
        - debug
  jpa:
    open-in-view: false
    show-sql: true
  flyway:
    clean-on-validation-error: true
server:
  error:
    include-message: always
    include-binding-errors: always
springdoc:
  show-actuator: true
management:
  endpoint:
    health:
      show-details: when_authorized